app:
  build: .
  ports:
    - 3099:3000
    - 8099:8080
  environment:
    NODE_ENV: development
    NODE_PORT: 3000
  env_file:
    - ./secrets.list
  volumes:
    - ./:/var/www
    - ../npm/:/npm
  #command: sleep infinity
  command: npm run dev
  links:
    - mysql
mysql:
  environment:
    TERM: xterm
  image: mariadb:10.1
  env_file:
    - ./mysql.list
  volumes:
    - ../volumes/blog-mysql:/var/lib/mysql
